- spinnaker_testbase/__init__.py
- spinnaker_testbase/base_test_case.py
- spinnaker_testbase/root_test_case.py
- spinnaker_testbase/test_no_job_destroy.py
updated baseTestCase
Moved JobDetroy check
> Test base2

- spinnaker_testbase/base_test_case.py
- spinnaker_testbase/root_test_case.py
Depends on 
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/765
use the ProvenanceReader
> Proveance reader

- spinnaker_testbase/root_test_case.py
part of https://github.com/SpiNNakerManchester/PACMAN/pull/371
> Making the configs truly global 

- spinnaker_testbase/root_test_case.py
- spinnaker_testbase/script_checker.py
Dont log if you are going to skiptest.
tested by 
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/no_log_skip/1/pipeline
> push skip_exceptions one level higher

- spinnaker_testbase/base_test_case.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/172
> Global data new

- .github/workflows/python_actions.yml
- .pylintrc
- spinnaker_testbase/base_test_case.py
- spinnaker_testbase/root_script_builder.py
- spinnaker_testbase/root_test_case.py
- spinnaker_testbase/script_checker.py
- spinnaker_testbase/test_no_job_destroy.py
tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/98
> Pylint fix

- .github/workflows/python_actions.yml
- .pylintrc
- requirements-test.txt
- requirements.txt
- setup.py
- spinnaker_testbase/__init__.py
- spinnaker_testbase/_version.py
- spinnaker_testbase/base_test_case.py
- spinnaker_testbase/root_script_builder.py
- spinnaker_testbase/root_test_case.py
- spinnaker_testbase/script_checker.py
- spinnaker_testbase/test_no_job_destroy.py
- spinnaker_testbase/test_scripts_header
- unittests/__init__.py
- unittests/test_import_all_test.py
part of https://github.com/SpiNNakerManchester/IntegrationTests/pull/180
> apply apache license with single date

- spinnaker_testbase/base_test_case.py
- spinnaker_testbase/root_script_builder.py
- spinnaker_testbase/root_test_case.py
- spinnaker_testbase/script_checker.py
Following on from SpiNNakerManchester/SpiNNUtils#223
> More of the minor fixes

- spinnaker_testbase/test_no_job_destroy.py
needed for https://github.com/SpiNNakerManchester/IntegrationTests/pull/191
> Remove installed

- spinnaker_testbase/base_test_case.py
yesterdays report changed exposed this hack.
https://github.com/SpiNNakerManchester/sPyNNaker/pull/1343 removes its only use.
Not fixing as there is a better way!
> remove hack no longer needed

- .github/workflows/python_actions.yml
- .ratexcludes
- doc/doc_requirements.txt
part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1075
> Move DataType to FEC. Archive DataSpecification

- unittests/test_report.py
> setUp is not a class method

- doc/source/conf.py
- doc/source/index.rst
remove https://dataspecification.readthedocs.io link(s)
> remove dataspecification link

- setup.cfg
- spinnaker_testbase/_version.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/236
> Version bump

- spinnaker_testbase/root_test_case.py
part of https://github.com/SpiNNakerManchester/sPyNNaker/pull/1380
> Raise skiptest

- .github/workflows/python_actions.yml
- setup.cfg
- setup.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/260
> Python3.12

- spinnaker_testbase/py.typed
This file allow mypy to test this directory
> add py.typed marker

- .github/workflows/python_actions.yml
- spinnaker_testbase/root_test_case.py
This brings TestBase in line with the main repositories.
includes a small change to fix a pylint issue found
> Use the global python_check.yml

- .github/workflows/python_actions.yml
- mypy.bash
- mypyd.bash
- spinnaker_testbase/base_test_case.py
- spinnaker_testbase/ping.py
- spinnaker_testbase/root_script_builder.py
- spinnaker_testbase/root_test_case.py
- spinnaker_testbase/script_checker.py
- spinnaker_testbase/test_no_job_destroy.py
- unittests/test_import_all_test.py
- unittests/test_report.py
Adds running mypy on main spinnaker_testbase code including unittests
- adds bash files to run mypy locally
- modifies pyproject.toml to ignore scipy and matplotlib
verified by https://github.com/SpiNNakerManchester/IntegrationTests/pull/313
> Mypy on spinnaker_testbase

- spinnaker_testbase/root_test_case.py
- spinnaker_testbase/test_no_job_destroy.py
global report folder move in https://github.com/SpiNNakerManchester/SpiNNUtils/pull/328
> global reports and error file
